[project]
name = "package_b"
version = "0.0.1"
readme = "README.md"
license = "MIT"
authors = [{ name = "Pedro Ten√≥rio" }]
dependencies = []

[project.scripts]
package_b = "titan.mod_b:func_b"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ['./src/titan']

[tool.ruff]
extend = '../../pyproject.toml'

[tool.pyright]
extends = '../../pyproject.toml'