[project]
name = "noinit-extension-a"
version = "0.0.1"
description = "noinit-extension-a"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
package-dir = { "" = "." }
